/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

 // @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: 'doc',
      id: "index",
      label: 'Home',
    },
    {
      type: 'category',
      label: 'Blocks',
      collapsible: true,
      collapsed: true,
      items: [
        'blocks/barrel', 'blocks/crucible', 'blocks/sieve', 'blocks/miscellaneous'
      ],
    },
    {
      type: 'category',
      label: 'Items',
      collapsible: true,
      collapsed: true,
      items: [
        'items/crooks', 'items/dolls', 'items/hammers', 'items/miscellaneous'
      ],
    },
    {
      type: 'category',
      label: 'Configuration',
      collapsible: true,
      collapsed: true,
      items: [
        'configuration/configuration', 'configuration/crafttweaker', 'configuration/data_pack', 'configuration/kubejs'
      ],
    },
    {
      type: 'doc',
      id: "changelog",
      label: 'Changelog',
    },
    {
      type: 'category',
      label: 'Versions',
      collapsible: true,
      collapsed: true,
      items: [
        {
          "type": "link",
          "label": "Latest",
          "href": "/exnihilosequentia"
        },
        {
          "type": "link",
          "label": "4.2.0",
          "href": "/exnihilosequentia/4.2.0"
        }
      ]
    }
  ],

};

module.exports = sidebars;
